config/routes.rb
Rails.application.routes.draw do
  mount Admin::Api::Init, at: "/admin/"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'book', to: 'book#index'
  get 'book/borrow', to: 'book#create'
  post 'book/borrow', to: 'book#store'
  get 'book/pdf', to: 'book#exportpdf'
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user

    validates_presence_of :cover_book
    mount_uploader :cover_book, BookUploader
end

app/controllers/admin/api/v1/books/resources/books.rb
class Admin::Api::V1::Books::Resources::Books < Grape::API
    resource :books do
        desc "Get List Books"
        oauth2 "super_admin"
        params do
            optional :q, type: String, desc: "Your key search"
        end

        get "/" do
            key = params.q
            p key
            unless key.present?
                data = Book.all
            else
                data = Book.where("name ILIKE ?", params.q)
            end
            present :books, data, with: Admin::Api::V1::Users::Entities::Books
        end

        desc "Save Books"
        oauth2 "super_admin"
        params do
            requires :name, type: String
            requires :cover_book,type: File
            requires :user_id
        end
        post "/" do
            user = User.find(params[:user_id])
            error!("User not found", env["api.response.code"] = 422) unless user.present?

            book = Book.new
            book.name = params.name
            book.cover_book = params.cover_book
            book.user_id = user.id
            error!(book.errors) unless book.save
            env["api.response.message"] = "Book saved"
            present :books, book, with: Admin::Api::V1::Users::Entities::Books
        end
    end
end

app/controllers/admin/api/v1/books/routes.rb
require_relative '../../../../error_formatter.rb'
require_relative '../../../../success_formatter.rb'
module Admin
  module Api
    module V1
      module Books
        class Routes < Grape::API
          formatter :json, SuccessFormatter
          error_formatter :json, ErrorFormatter

          mount Admin::Api::V1::Books::Resources::Books
        end
      end
    end
  end
end

app/controllers/admin/api/v1/users/entities/books.rb
class Admin::Api::V1::Users::Entities::Books < Grape::Entity
    expose :id
    expose :name
    expose :url_cover, as: :cover_book
    expose :user_id

    private
    def url_cover
        object.try(:cover_book).try(:url)
    end
end

app/controllers/book_controller.rb
class BookController < ApplicationWebController
    def index
        @books = Book.all
        respond_to do |format|
            format.xlsx
            format.html
        end
    end

    def create
        p params.permit(:book_id, :user_id, :total_day)
        # @current_user = current_user

        # @product = Book.new()
        # @product.name = params.name
        # # @product = @current_user.products.new(product_params)

        # if @product.save
        #     redirect_to @product
        #   else
        #     render 'create'
        # end
        @books = Book.pluck(:name,:id)
        @bookData = @books.to_a
        @users = User.pluck(:name,:id)
        @datas = @users.to_a

        render 'create'
    end

    def store
    
    end

    def exportpdf
        @books = Book.all
        respond_to do |format|
            format.html
            format.pdf do
                pdf = BookPdf.new(@books)
                send_data pdf.render, filename: "book.pdf",
                                        type: "application/pdf",
                                        disposition: "inline"
            end
        end
    end

    private
    def product_params
        params.require(:product).permit(:product_name, :category, :description, :price, :contact_email, :cover, :term)
    end
end

app/views/book/_form.html.erb
<%= form_with do |form| %>
    <div class="form-group">
        <%= form.label :book_id, "Judul Buku" %><br>
        <%= form.select :book_id, @bookData %>
    </div>
    <div class="form-group">
        <%= form.label :total_day, "Jumlah Hari" %><br>
        <%= form.text_field :total_day, :class => 'form-control', placeholder: "Total Day" %>
    </div>
    <div class="form-group">
        <%= form.label :user_id, "User" %><br>
        <%= form.select :user_id, @datas %>
    </div>

    <%= form.submit "Submit", :class => 'btn btn-primary' %>
<% end %>

app/views/book/create.html.erb
<div class="container">
    <h1>Pinjam Buku</h1>
    <%= render 'form' %>
</div>

app/views/book/index.html.erb
<div>
    <button class="lead mt-4"><%= link_to 'Export Excel', book_path(format: :xlsx) %></button>
    <button class="lead mt-4"><%= link_to 'Export Pdf', book_pdf_path(format: :pdf) %></button>
</div>
<table border="1">
    <thead>
        <tr>
            <th>No</th>
            <th>Judul Buku</th>
            <th>Link Gambar Buku</th>
            <th>User Name</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <% @books.each_with_index do |data, index| %>
            <tr>
                <td><%= index+=1 %></td>
                <td><%= data.name %></td>
                <td><%= data.cover_book %></td>
                <td><%= data.user.name %></td>
                <td>
                    <%# <%= link_to 'Hapus', todo_destroy_path(data.id), data: { confirm: 'Ingin menghapus task ini?' }, method: :delete %>
                    <%# <%= link_to 'Edit', todo_edit_path(data.id) %> %> %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>